### ISSUE TITLE
ChromiumRemoteConnection object has no attribute '_url'

### ISSUE THREAD

**Issue by jk-85** [markmelnic/stealthenium#3] opened 2024-11-26 16:13 UTC
I got this when trying to integrate stealthenium into my project:

I use:
Chromium 131.0.6778.85 snap
ChromeDriver 131.0.6778.85 (3d81e41b6f3ac8bcae63b32e8145c9eb0cd60a2d-refs/branch-heads/6778@{#2285})

> Traceback (most recent call last):
  File "/home/user/amazon/amazon.py", line 103, in <module>
    stealth(driver,
  File "/home/user/.local/lib/python3.10/site-packages/stealthenium/__init__.py", line 46, in stealth
    with_utils(driver, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/stealthenium/utils.py", line 6, in with_utils
    evaluateOnNewDocument(
  File "/home/user/.local/lib/python3.10/site-packages/stealthenium/wrapper.py", line 20, in evaluateOnNewDocument
    execute_cdp_cmd(driver, "Page.addScriptToEvaluateOnNewDocument", {
  File "/home/user/.local/lib/python3.10/site-packages/stealthenium/cdp.py", line 5, in execute_cdp_cmd
    url = driver.command_executor._url + resource
AttributeError: 'ChromiumRemoteConnection' object has no attribute '_url'

**Comment by jk-85** [comment] 2024-11-26 16:35
Ooops, the first issue created before me has the same problem. Will investigate that instead.

**Comment by jk-85** [comment] 2024-11-26 18:05
That did the job for me, I just set a port-number:

> browser_driver = Service('/usr/lib/chromium-browser/chromedriver', port=5600)
driver = webdriver.Chrome(service=browser_driver, options=options)
driver.command_executor._url = "http://127.0.0.1:5600"

**Comment by markmelnic** [comment] 2024-11-26 19:37
Duplicate of #2, let's move there.

**Closed as completed by markmelnic** 2024-11-26 19:37 UTC
Labels: duplicate

**Comment by RLuckyX** [comment] 2024-12-13 00:53
> That did the job for me, I just set a port-number:
> 
> > browser_driver = Service('/usr/lib/chromium-browser/chromedriver', port=5600)
> > driver = webdriver.Chrome(service=browser_driver, options=options)
> > driver.command_executor._url = "http://127.0.0.1:5600"

I tried to connect to existing chrome profile i first open that chrome profile via remte debugging using subprocess and than using that debugger address and port t connect with it but now i want to use stealth i have problem in connecting with same it throws same error.

Any suggestion or help is appreciated
